twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/styles': styles
        # point this wherever your images live
        '%kernel.project_dir%/assets/img': img

when@test:
    twig:
        strict_variables: true
