vich_uploader:
    db_driver: orm

    mappings:
        reservations:
            uri_prefix: /uploads/contracts
            upload_destination: '%kernel.project_dir%/public/uploads/contracts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
